### ISSUE TITLE
Install env

### ISSUE THREAD

**Issue by Bobchenyx** [nlokeshiisc/GCFL_Release#1]
Could you please specify python and torch version?

I'm getting trouble with installing the package "imagecorruptions".

Kindly asking for a guide with your local env. or could you provide a requirement.txt ?

**Comment by nlokeshiisc** [comment]
Hi,

Very sorry for the delay. Somehow, this issue slipped my sight in may mailbox. I have added a gcfl.yml file, which will help you install all the necessary libraries to run GCFL.
