### ISSUE TITLE
Import issues for OrthogonalMP_REG_Parallel_V1_ED

### ISSUE THREAD

**Issue by markusbujotzek** [nlokeshiisc/GCFL_Release#2]
Hey,

I wanted to run the GCFL code, but unfortunately, I cannot run the code with the given command `python Federated/main.py --config Config_files/config.py`.

I installed all necessary dependecies, however, I still run into the following import issue:
```
File "/home/[...]/GCFL_Release/Federated/cords/gradmatchstrategy.py", line 6, in <module>
    from .helpers import OrthogonalMP_REG_Parallel_V1_ED
ModuleNotFoundError: No module named 'cords.helpers'
```

By taking a look into the repository, the error makes perfectly sense as there is no helpers.py file in /GCFL_Release/Federated/cords/ directory.

Could you please clarify how the code is still functional and how I can get rid of this error?

Thank you very much!

**Comment by nlokeshiisc** [comment]
Hi,

I have added the helpers.py file, so the code should run now. Thanks very much for flagging this issue.
